### ISSUE TITLE
Support optional fields in proto v3

### ISSUE THREAD

**Issue by RoarkeRandall** [kei2100/protoc-gen-marshal-zap#32]
Hello,

First, thanks for keeping this fork updated. 

We tried to use an optional field in proto v3 and buf gave us an error saying this plugin doesn't support optional fields. Would it be possible to add support? 

Cheers,
Roarke

**Comment by VicNgu** [comment]
Following up on this.
Say we have this contract:
`message EventComponent {
  optional ComponentProfile component_profile = 1;
}
`

We expect this to be able to generate the pb.go files with no errors.

When we run the buf generate command and reference the zap-marshaler plugin, we get this error:
Warning: plugin "zap-marshaler" does not support required features.
  Feature "proto3 optional" is required by 1 file(s):
    int/container/container.proto

**Comment by kei2100** [comment]
@VicNgu 
Thanks for the follow-up.

I see, this is not a buf issue, but rather the marshal-zap plugin was not able to support the optional field that was enabled in protocol buffers 3.15.

I have implemented support for optional fields in a pull request here #33 . I'll release a new version soon, so stay tuned.

**Comment by kei2100** [comment]
@RoarkeRandall @VicNgu 
Released support for `optional` fields in proto v3.
https://github.com/kei2100/protoc-gen-marshal-zap/releases/tag/v0.2.0

If you still have problems, please reopen this issue and report them.

**Comment by RoarkeRandall** [comment]
Awesome! We’ll test it out soon.
