### ISSUE TITLE
Support buf in the future?

### ISSUE THREAD

**Issue by haunt98** [kei2100/protoc-gen-marshal-zap#38]
Buf is the new prototool :D 

Also add buf support is easy as I can fork your repo and add to my buf.build repo in here https://github.com/haunt98/protoc-gen-marshal-zap/commit/8a9593902b9d4d9d7ad0958a60cbd408123f88c7

You can see my buf.build repo here https://buf.build/haunt98/marshal-zap

**Comment by kei2100** [comment]
Thank you for the example.

Now I don't use buf, so I hadn't considered supporting it, 
but I will try buf next time I have time and consider it.

**Comment by kei2100** [comment]
Hello, @haunt98.

Released buf support in [v0.3.0](https://github.com/kei2100/protoc-gen-marshal-zap/releases/tag/v0.3.0).
For more details, see https://github.com/kei2100/protoc-gen-marshal-zap#using-buf.
I'm also applying for a [remote plugin](https://docs.buf.build/bsr/remote-plugins/usage) here https://github.com/bufbuild/plugins/issues/370

**Comment by haunt98** [comment]
Thank you @kei2100! I have tried your buf.build, so far so good :D
